### ISSUE TITLE
Repaint flickering

### ISSUE THREAD

**Issue by jimenezjose** [jimenezjose/Micromouse_Simulator#35]
The animation flickers for the reason that MazeGUI extends JFrame and we are overriding the paint method. The JFrame paint method is not double buffered hence for the flickering. I am thinking about changing the parent from JFrame to JPanel because JPanel uses double buffering via paintComponent.

**Comment by jimenezjose** [comment]
I created a new branch "Animation" to independently smoothen the graphics of the GUI.

**Comment by srini236** [comment]
> The animation flickers for the reason that MazeGUI extends JFrame and we are overriding the paint method. The JFrame paint method is not double buffered hence for the flickering. I am thinking about changing the parent from JFrame to JPanel because JPanel uses double buffering via paintComponent. <

exactly what i am doing; when i typed in setDoubleBuffered(true) it would not recognize the method because its a JFrame, not a JPanel. Thanks for confirming though.

**Comment by srini236** [comment]
Tried out creating the north panels, south panels and all buttons outside the class, inside the main method and passed the buttons through the constructor for the action performed method to recognize them. Changed the maze gui class to extend from JPanel so double buffer on the paint method can be used, and inside the main method created a JFrame and added al the 3 panels (maze gui, north and south panels). The result is that the grid lines flash for a moment and dissapear upon creation of the frame, then the entire maze is empty (two grey boxes). 

Will probably revert those changes and make an ofscreen image and paint everything to that then copy  the image back to the screen. 

Or make an outer frame class, make the maze gui class an inner class extending a JPanel. Add the north , south panels as variables of outer class.
